/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example;

/**
 *
 * @author NURFAUZIYAH
 */

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

public class ViewKaryawan extends javax.swing.JFrame {
    
    private int selectedKaryawanId = -1;
    
    public ViewKaryawan() {
        initComponents();
        setTitle("SmartHR");
        loadKaryawanToTable();
    }
    
    private void loadKaryawanToTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tabelKaryawan.getModel();
        tableModel.setRowCount(0);
        ControlKaryawan kontrol = new ControlKaryawan();
        List<Karyawan> karyawanList = kontrol.getAllKaryawan();
        for(Karyawan karyawan : karyawanList) {
            tableModel.addRow(new Object[]{
                karyawan.getID(), 
                karyawan.getNama(), 
                karyawan.getJabatan(), 
                karyawan.getNo_telp(), 
                karyawan.getAlamat(), 
                karyawan.getStatus()
            });
        }
    }
    
    private int getSelectedKaryawanId(String nama, String jabatan, String no_telp) {
        ControlKaryawan kontrol = new ControlKaryawan();
        List<Karyawan> karyawanList = kontrol.getAllKaryawan();
        
        for(Karyawan karyawan : karyawanList) {
            if(karyawan.getNama().equals(nama) && karyawan.getJabatan().equals(jabatan) && karyawan.getNo_telp().equals(no_telp)) {
                return karyawan.getID();
            }
        }
        
        return -1;
    }
    
    private void resetForm() {
        iNama.setText("");
        iJabatan.setText("");
        iNo_telp.setText("");
        iAlamat.setText("");
        iStatus.setSelectedIndex(0); // Reset combo box to default
        selectedKaryawanId = -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iNama = new javax.swing.JTextField();
        iAlamat = new javax.swing.JTextField();
        iJabatan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        iNo_telp = new javax.swing.JTextField();
        iStatus = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 167, 115));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 112, 80));
        jLabel1.setText("MANAGE DATA KARYAWAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 112, 80));
        jLabel2.setText("JABATAN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 112, 80));
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 112, 80));
        jLabel4.setText("NOMOR TELEPON");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 112, 80));
        jLabel5.setText("ALAMAT");

        iNama.setForeground(new java.awt.Color(66, 112, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 112, 80));
        jLabel6.setText("STATUS");

        iStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aktif", "nonaktif" }));

        btnEdit.setBackground(new java.awt.Color(255, 210, 51));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("UPDATE");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(51, 196, 30));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(33, 125, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(249, 25, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tabelKaryawan.setForeground(new java.awt.Color(66, 112, 80));
        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAMA", "JABATAN", "NO TELP", "ALAMAT", "STATUS"
            }
        ));
        tabelKaryawan.setGridColor(new java.awt.Color(66, 112, 80));
        tabelKaryawan.setSelectionBackground(new java.awt.Color(66, 112, 80));
        tabelKaryawan.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKaryawan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iAlamat)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iNo_telp, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(iJabatan)
                            .addComponent(iNama))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(iNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iNo_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String nama = iNama.getText().trim();
        String jabatan = iJabatan.getText().trim();
        String no_telp = iNo_telp.getText().trim();
        String alamat = iAlamat.getText().trim();
        String status = iStatus.getSelectedItem().toString();
        
        if(nama.isEmpty() || jabatan.isEmpty() || no_telp.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean isDataExist = false;
        DefaultTableModel model = (DefaultTableModel) tabelKaryawan.getModel();
        int rowCount = model.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String namaTabel = (String) model.getValueAt(i, 1);
            String jabatanTabel = (String) model.getValueAt(i, 2);
            String noTelpTabel = (String) model.getValueAt(i, 3);
            if (nama.equals(namaTabel) && jabatan.equals(jabatanTabel) && no_telp.equals(noTelpTabel)) {
                isDataExist = true;
                break;
            }
        }
        
        if (isDataExist) {
            JOptionPane.showMessageDialog(this, "Data karyawan sudah ada!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Karyawan karyawan = new Karyawan();
                karyawan.setNama(nama);
                karyawan.setJabatan(jabatan);
                karyawan.setNo_telp(no_telp);
                karyawan.setAlamat(alamat);
                karyawan.setStatus(status);

                ControlKaryawan kontrol = new ControlKaryawan();
                kontrol.saveKaryawan(karyawan);

                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadKaryawanToTable();
                resetForm();
            } catch(Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
//        if(selectedKaryawanId != -1) {
//            JOptionPane.showMessageDialog(this, "Data ini sudah ada! Silakan lakukan update.", "Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        // TODO add your handling code here:
        int selectedRow = tabelKaryawan.getSelectedRow();
        if(selectedRow != -1) {
            String nama = tabelKaryawan.getValueAt(selectedRow,1).toString();
            String jabatan = tabelKaryawan.getValueAt(selectedRow,2).toString();
            String no_telp = tabelKaryawan.getValueAt(selectedRow,3).toString();
            String alamat = tabelKaryawan.getValueAt(selectedRow,4).toString();
            String status = tabelKaryawan.getValueAt(selectedRow,5).toString();
            
            
            iNama.setText(nama);
            iJabatan.setText(jabatan);
            iNo_telp.setText(no_telp);
            iAlamat.setText(alamat);
            iStatus.setSelectedItem(status);
            
            selectedKaryawanId = getSelectedKaryawanId(nama, jabatan, no_telp);
        }
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(selectedKaryawanId == -1) {
            JOptionPane.showMessageDialog(this,"Pilih data yang ingin diperbarui.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String nama = iNama.getText().trim();
        String jabatan = iJabatan.getText().trim();
        String no_telp = iNo_telp.getText().trim();
        String alamat = iAlamat.getText().trim();
        String status = iStatus.getSelectedItem().toString();
        
        if(nama.isEmpty() || jabatan.isEmpty() || no_telp.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            ControlKaryawan kontrol = new ControlKaryawan();
            Karyawan karyawan = kontrol.getKaryawanById(selectedKaryawanId);
            karyawan.setNama(nama);
            karyawan.setJabatan(jabatan);
            karyawan.setNo_telp(no_telp);
            karyawan.setAlamat(alamat);
            karyawan.setStatus(status);
            
            kontrol.updateKaryawan(karyawan);
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadKaryawanToTable();
            resetForm();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
         resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedKaryawanId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirmed = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION) {
            try {
                ControlKaryawan kontrol = new ControlKaryawan();
            
                Karyawan karyawan = kontrol.getKaryawanById(selectedKaryawanId);
                if(karyawan != null) {
                    kontrol.deleteKaryawan(karyawan);
                    JOptionPane.showMessageDialog(this,"Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    loadKaryawanToTable();
                    resetForm();
                }
            } catch(Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField iAlamat;
    private javax.swing.JTextField iJabatan;
    private javax.swing.JTextField iNama;
    private javax.swing.JTextField iNo_telp;
    private javax.swing.JComboBox<String> iStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKaryawan;
    // End of variables declaration//GEN-END:variables
}
